#!/usr/bin/env bash

set -euo pipefail

# screensaver settings
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -float 0.0

# screenshot settings
defaults write com.apple.screencapture location ~
defaults write com.apple.screencapture disable-shadow -bool true

# trackpad settings
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults write com.apple.AppleMultitouchTrackpad Dragging -int 1
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true

# clock display format
defaults write com.apple.menuextra.clock DateFormat "EEE MMM d  h:mm a"
defaults write com.apple.menuextra.clock IsAnalog -bool false

# Show battery percentage free.
defaults write com.apple.menuextra.battery ShowPercent -bool true

# Show mounted devices on desktop.
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true

# Never restore windows after reboot.
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

# Quit printer app after done.
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Expanded save/print dialogs by default.
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Save to disk by default (not icloud).
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# This isn't dangerous and done frequently.
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Unhide library folder in finder.
chflags nohidden ~/Library

if groups | grep -wq admin; then
    # Disable boot sound.
    sudo nvram SystemAudioVolume=%80

    # Add brew installed shells to system.
    for name in bash zsh; do
        path=/usr/local/bin/$name
        if ! grep -q "$path" /etc/shells; then
            sudo tee -a /etc/shells >/dev/null <<<"$path"
        fi
    done
fi

chsh -s /usr/local/bin/zsh

temp_dir=$HOME/.local/tmp
mkdir -p "$temp_dir"
chmod 700 "$temp_dir"
