#!/usr/bin/env bash

set -eu

if ! which gcc >/dev/null; then
    xcode-select --install
fi

if ! which brew >/dev/null; then
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install | ruby
fi

xargs -r brew install <./packages/formulae
xargs -r brew install --cask <./packages/casks
