#!/usr/bin/env bash

set -eu

# Install command-line tools.
if [[ ! -x /usr/bin/gcc ]]; then
    xcode-select --install
fi

if [[ ! -x /usr/local/bin/brew ]]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

xargs -r brew install <./packages/formulae
xargs -r brew install --cask <./packages/casks
